name: Core workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        with:
          cmd: test # will run `yarn test` command
    # steps:
    # - uses: actions/checkout@v1
    # - name: Use Node.js 12.x
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: "12.x"
    # - name: yarn install, and test
    #   run: |
    #     yarn install
    #     yarn test
    #   env:
    #     CI: true
